name: Sync mirror beta
on:
#  schedule:
#    - cron:  '0 1 * * *'
  workflow_dispatch:

jobs:
  Prepare:
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'Armbian' }}
    outputs:
      matrix: ${{steps.list_dirs.outputs.matrix}}
    steps:

      - name: Prepare matrix
        id: list_dirs
        run:
          echo ::set-output name=matrix::$(for x in $(wget -qO - https://www.armbian.com/userdata.csv | cut -d"/" -f1 | uniq); do echo $x; done|jq -cnR '[inputs | select(length>0)]' | jq)

  Build: # short name because GH will expand with the matrix values
    needs: [ Prepare ]
    runs-on: ubuntu-latest
    timeout-minutes: 480
    strategy:
      max-parallel: 4
      fail-fast: false # let other jobs try to complete if one fails
      matrix: 
        node: ${{fromJson(needs.Prepare.outputs.matrix)}}

    steps:
      - name: Download from Armbian storage
        id: image-build
        run: |
          set +e
          BOARD="${{ matrix.node }}"
          FILES=$(wget -qO - https://www.armbian.com/userdata.csv | grep ${BOARD}"/" | grep -v nightly | cut -d"|" -f2) # exclude nightly
          for FILE in ${FILES[@]}
          do
            if ! wget -q --spider --timeout=15 --tries=3 --retry-connrefused https://github.com/"${{ github.repository }}"/releases/download/${FILE} ; then
                echo "Downloading ..."
                wget https://imola.armbian.com/dl/$FILE                
                echo "UPLOAD=true" >> $GITHUB_ENV
            fi
          done
      - name: Upload artefacts
        if: ${{ env.UPLOAD == 'true' }}
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: Armbian*
          tag: "${{ matrix.node }}/archive"
          overwrite: true
          file_glob: true
          body: "This is Armbian file mirror at Github"
